### ISSUE TITLE
English to Korean Translation

### ISSUE THREAD

**Issue by PenPoint** [AluminiumTech/SpecsBoss#9]
Test comment.

Make sure translations go like

[English Text] -> [Korean Text]

"Run SpecsBoss with a 64 Bit processor" -> [64비트 프로세서로 SpecsBoss 실행하기]
"Achievement Get - AMD64" -> [업적 달성 - AMD64]
"Run SpecsBoss with a system designed for gaming. There's nothing quite as satisfying as getting over 60fps in Crysis!" -> [게이밍을 위해 탄생한 시스템으로 SpecsBoss 실행하기 - 크라이시스에서 60프레임을 넘는 것보다 만족스러운 것은 없습니다!]
"Achievement Get - Gaming Ready" -> [업적 달성 - Gaming Ready]
"Run SpecsBoss with just enough RAM to run Windows." -> [Windows가 겨우 돌아가는 적은 RAM으로 SpecsBoss 실행하기]
"Achievement Get - Just Enough RAM" -> [업적 달성 - 겨우 돌아가는 RAM]
"Run SpecsBoss with a monsterous amount of RAM. This is beyond unreasonable! It's madness!" -> [어마어마한 양의 RAM으로 SpecsBoss 실행하기 - 이성의 한계를 넘었습니다! 제정신이 아닙니다!]
"Achievement Get - Monsterous RAM" -> [업적 달성 - 무시무시한 RAM]
"Run SpecsBoss with a multi core processor." -> [멀티코어 프로세서로 SpecsBoss 실행하기]
"Achievement Get - Multi core" -> [업적 달성 - 멀티코어]
"Run SpecsBoss with an eight core processor." -> [8코어 프로세서로 SpecsBoss 실행하기]
"Achievement Get - Octa core" -> [업적 달성 - 옥타코어]

-------------------------------

"About SpecsBoss" -> SpecsBoss 정보
"File" -> 파일
"Help" -> 도움말
"Go to Lithium Classic Website" -> Lithium Classic 누리집 방문
"New Window" -> 새 창
"Quit" -> 종료
"Version Release Notes" -> 버전 릴리즈 노트
"Report a Bug" -> 버그 제보하기
"Restart" -> 재시작
"Settings" -> 설정
"Go to Specs Boss Website" -> SpecsBoss 누리집 방문
"Specs Boss Wiki" -> SpecsBoss 위키
"Copyright Notice:
Intel Core and Intel Xeon are trademarks of Intel Corporation in the United States of America and other countries.
Windows is a copyright of Microsoft Corporation in the United States of America and other countries.
Radeon is a trademark of Advanced Micro Devices Incorporated in the United States of America and other countries.
GeForce, Quadro and Tesla are copyrights of Nvidia Corporation in the United States of America and other countries.
All other copyrights and trademarks are copyrights and trademarks of their respective owners." ->
Intel Core 및 Intel Xeon은 미합중국 및 기타 국가 소재 Intel Corporation의 상표입니다.
Windows는 미합중국 및 기타 국가 소재 Microsoft Corporation의 상표입니다.
Radeon은 미합중국 및 기타 국가 소재 Advance Micro Devices Incorporated의 상표입니다.
GeForce, Quadro 및 Tesla는 미합중국 및 기타 국가 소재 Nvidia Corporation의 상표입니다.
모든 기타 저작권 및 상표는 개별 소유자의 저작권 및 상표입니다.

**Comment by AluminiumTech** [comment]
"About SpecsBoss" -> [Korean Text]
"File" -> 
"Help" ->
"Go to Lithium Classic Website" ->
"New Window" ->
"Quit" ->
"Version Release Notes" ->
"Report a Bug" ->
"Restart" ->
"Settings" ->
"Go to Specs Boss Website" ->
"Specs Boss Wiki" ->
"Copyright Notice: 
Intel Core and Intel Xeon are trademarks of Intel Corporation in the United States of America and other countries.
Windows is a copyright of Microsoft Corporation in the United States of America and other countries.
Radeon is a trademark of Advanced Micro Devices Incorporated in the United States of America and other countries.
GeForce, Quadro and Tesla are copyrights  of Nvidia Corporation in the United States of America and other countries.
All other copyrights and trademarks are copyrights and trademarks of their respective owners." ->

**Comment by AluminiumTech** [comment]
Added translations for the Menus and the Achievements

**Comment by AluminiumTech** [comment]
![tr4](https://cloud.githubusercontent.com/assets/14107316/24079915/91afe2e0-0cce-11e7-95c9-3ccd8a20ef55.PNG)
![tr5](https://cloud.githubusercontent.com/assets/14107316/24079914/91afd142-0cce-11e7-8651-5e8d16f6d2a3.PNG)
![tr6](https://cloud.githubusercontent.com/assets/14107316/24079912/91ae971e-0cce-11e7-8367-70216960f54a.PNG)
![tr7](https://cloud.githubusercontent.com/assets/14107316/24079913/91aecb08-0cce-11e7-8887-417bb7b2f546.PNG)

You can ignore the "value" bit. That's for me.

**Comment by PenPoint** [comment]
1st screenshot:
사용 가능한 RAM
빌드 종류
CPU 종류
CPU 클럭 속도
CPU 코어 수
CPU L2 캐시
CPU L3 캐시
CPU 제조사
CPU 이름
CPU 소켓
CPU 스레드 수
장치 이름
드라이버 버전
그래픽카드 이름
GPU 아키텍처
그래픽카드 종류
GPU 코드네임
VRAM 용량
전압 최대치
전압 최소치
운영 체제
OS 빌드
페이징 파일 크기
RAM 속도
Windows 릴리즈 버전
시스템 디렉터리
설치된 전체 RAM
사용자 이름
Windows 관리자

2nd screenshot:
초기 설정 진행 중...
SpecsBoss 준비 중... PC를 종료하지 마세요.
이것은 SpecsBoss가 나중에 더 빨리 실행될 수 있게 합니다.

3rd screenshot:
본 제품은 자동 업데이트가 내장되어 있습니다.
SpecsBoss의 업데이트가 가능합니다!

RC 버전
SpecsBoss 업데이트를 받을 수 없습니다.
릴리즈 노트
**Release Notes for ABC -> ABC에 대한 릴리즈 노트** DIFFERENT WORD ORDER!
확인

4th screenshot:
AluminiumCoreLibrary 버전
빌드 일자
SpecsBoss는 오픈소스 소프트웨어를 기반으로 제작되었습니다.
버그 제보하기
SpecsBoss 버전
AluminiumCoreLibrary GitHub 페이지 방문하기
LithiumClassic GitHub 페이지 방문하기
SpecsBoss GitHub 페이지 방문하기

**Comment by AluminiumTech** [comment]
![tr8](https://cloud.githubusercontent.com/assets/14107316/24100743/7da338aa-0db0-11e7-9ba5-95dcc8bf43ab.PNG)
![tr9](https://cloud.githubusercontent.com/assets/14107316/24100742/7da23c5c-0db0-11e7-849c-6b16d1d0f5c7.PNG)
![tr10](https://cloud.githubusercontent.com/assets/14107316/24100760/9aceedc0-0db0-11e7-9d99-4945c969bf26.PNG)
![tr11](https://cloud.githubusercontent.com/assets/14107316/24100800/b71b0284-0db0-11e7-8443-46229f3c1ccf.PNG)

**Comment by PenPoint** [comment]
1st screenshot)
1] 약관에 동의하기 전에 사용권 계약을 읽어 주세요.
2] 취소
3] 사용권

2nd screenshot)
AluminiumTech 라이센스
Copyright (c) 2017 AluminiumTech
... too hard, I'll do it later :/

3rd screenshot)
도구 및 기능
다음의 멋진 앱들을 통해 SpecsBoss에 기능을 추가해 보세요.
설정 적용하기
완료
벤치마크 유틸리티 설치하기
설정 메뉴
환경 설정
원격 수집 데이터
[LONG PART BEGIN]
SpecsBoss는 이 프로그램을 사용할 때 더 나은 경험을 위해 일부 데이터를 수집합니다.
수집하는 데이터는 다음과 같습니다.
* 컴퓨터 하드웨어 사양
* 앱 사용 데이터
* SpecsBoss 업데이트 관련 정보
* Windows 설치 관련 정보
SpecsBoss는 그 어떤 회사와도 위 정보를 공유하지 않으며, 모든 정보는 그 어떤 목적으로도 다른 컴퓨터나 장치에 전송 및 저장되지 않고 이 컴퓨터에만 사용됩니다.
[LONG PART OVER]
어두운 테마
서드파티 소프트웨어 사용 관련

4th screenshot)

**SpecsBoss**
새로운 SpecsBoss 앱은 C#로도 코딩되고 있습니다.

**소스 코드 빌드 및 기여하기**
= Visual Studio 2017을 설치하거나 최신 버전으로 업그레이드하고 .NET 애플리케이션 패키지가 설치되어 있는지 확인하세요.
= 이 저장소를 복사하세요.
= PC로 붙여넣으세요.
= 변경하고 싶은 부분을 반영하세요.
= 작성한 코드가 어떤 것인지에 대해 pull 요청을 제출하세요.
= 접수될 때까지 기다려 주세요. SpecsBoss 마스터 분기에 추가할 수도 있습니다.

**번역**
SpecsBoss가 본인의 언어로 지원되지 않고 있다면 GitHub Issues를 통해 Issue를 하나 열고 가능한 한 번역할 수 있는 모든 부분 및 언어를 기재하여 기여해 주세요.
